### ISSUE TITLE
User story - How to play instructions

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#11]
### Story

As a **player**, I can **easily understand the controls and rules of the game** so that I can **quickly start playing**.

### Acceptance Criteria

- Player should be able to access the game rules from the home screen
- Controls should be displayed in the rules
- Control should be clear for both mobile and desktop
- Display controls on screen when game first starts? 

### Tasks

- [x] Create the "Game rules" screen
- [x] List out rules clearly
- [x] Ensure controls are correct

**Comment by Nazek-Altayeb** [comment]
implementation plan 

- Create *public/scene_background_images* folder
- Insert *Welcome* and *Instructions* images inside
