### ISSUE TITLE
User story - Shooting

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#14]
### Story

As a **player**, I can **press a button/tap the screen** so that I can **shoot to hit an enemy**.

### Acceptance Criteria

- The solution should allow shooting on mobile and desktop
- Bullets should be removed when off screen or when they collide with an enemy

### Tasks

- [x] Create the bullet
- [x] Handle off-screen and collision removal of the bullet
- [ ] Choose how often the bullets can be fired
