### ISSUE TITLE
User story - Enemy behaviour

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#15]
### Story

As a **player**, I can **face enemies that vary in behaviour or speed** so that I can **feel challenged in the game**.

### Acceptance Criteria

- One enemy should move randomly around the screen
- Terminator enemy should move towards the player
- Should be able to spawn multiple enemies
- Difficulty progression will also be dealt with in #7 

### Tasks

- [x] Create a function to spawn an enemy
- [x] Add in functionality to make enemy move randomly
- [x] Add functionality to make enemy move towards user
- [x] Add ability for an enemy to shoot

**Comment by stephendawsondev** [comment]
This is done now!
