### ISSUE TITLE
User story - Toggle Sound

### ISSUE THREAD

**Issue by adamgilroy22** [stephendawsondev/j-day#31]
### Story

As a **player**, I can **toggle background music on and off** so that I can **be further immersed in the game**.

### Acceptance Criteria

- Music must be muted on page load
- A button must be present on the page that prompts the player to unmute and mute the music
- On clicking the button the music must either play or stop

### Tasks

- [x] Music files must be added to the repository
- [ ] A button must be created either within the game or on the site page allowing the player to mute or unmute the music
- [ ] Music must play/pause when the player clicks the button
- [ ] The button should change text to read either play or stop music depending on if the music is currently playing

**Comment by stephendawsondev** [comment]
@adamgilroy22 How is this one going? I saw that you were looking after bits of it. Is it working as expected?

**Comment by adamgilroy22** [comment]
@stephendawsondev  The music doesn't seem to be starting right away when I load the game but does start once a new scene is loaded or if the toggle music button is clicked twice. It seems as if the music is registering as playing so when the button is clicked once it mutes it and the second time resumes it but that would be the first time I hear it. I'm not sure if this is the same for everyone else or not. Other than that, the toggling of music is working on the home page!

**Comment by stephendawsondev** [comment]
We can test it a bit more later to see when it happens and what might need to be done to fix it.

**Comment by stephendawsondev** [comment]
It looks like it is still happening. I wonder if it could be resolved by passing a variable to each scene. We could have `playMusic: false,` or something like that. Then on each scene, there's a control (maybe we could switch it to an icon) where the user can toggle it again and it switches the boolean. Either that OR we make it a global variable so that it is accessible on every scene.

**Comment by adamgilroy22** [comment]
@stephendawsondev I think it's to do with where we're setting the variable. I've just run a quick test by moving the const outside of the return scene function and it works as expected again. I believe the issue's reappeared since we've allowed users to return to the menu from the instructions page

![image](https://github.com/stephendawsondev/j-day/assets/111069103/360f183e-8b17-4587-a46a-6c071cc674a9)

**Comment by stephendawsondev** [comment]
Taking a look at that, each time we go from one screen to another, we're essentially running it again, but we're never stopping the music. That leads to duplications. 

Have you tested the above solution? I'm not sure exactly why that would prevent it from playing, but good if it does 😅

**Comment by adamgilroy22** [comment]
Yeah, I think taking it out of the return scene stops it from playing every time the scene is loaded, whereas when it's put into the createWelcomeScene function it gets created when the game starts and when it's toggled off it stays off and there's not another instance of the sound created when the scene is loaded. I tested it and it works. Same when the game is quit, no music repeats or overlapping!
