### ISSUE TITLE
User story - Scoreboard

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#33]
### Story

As a **player**, I can **keep track of my high scores** so that I can **compete against myself**.

### Acceptance Criteria

- Separate scoreboard scene
- User can see a list of their previous scores
- The user can add their name to the score

### Tasks

- [ ] Create the scoreboard scene
- [ ] Style scoreboard page
- [ ]  User LocalStorage to store a list of scores
- [ ] Pull scores from local storage
- [ ] Write a new score (and username) to local storage
