### ISSUE TITLE
User story - Pause Menu

### ISSUE THREAD

**Issue by adamgilroy22** [stephendawsondev/j-day#36]
### Story

As a **player**, I can **pause the game while playing** so that I can **take a short break from playing or quit the game and return to the main menu**.

### Acceptance Criteria

- While the game is active, if the player presses a certain key (possibly P), the game should freeze and a pause menu should appear
- The pause menu should contain options to resume the game from where it was paused, quit the game, and toggle music
- When a player clicks to resume, they should pick up from exactly where the game was paused
- When a player clicks on quit, their game should end and they should be brought back to the home menu
- When a player clicks the button to toggle sound, music should either play or stop depending on its current state

### Tasks

- [ ] Pause menu scene to be created
- [ ] Pause menu should be activated when the player presses P during gameplay
- [ ] Pause menu should contain options to resume, quit, and toggle music
- [ ] When pause menu is active, gameplay should freeze
- [ ] Gameplay should resume when the resume option is selected
- [ ] Current game should end when the quit option is selected and player should be brought back to the main menu
- [ ] Music should either play or stop when the player clicks on toggle sound

**Comment by adamgilroy22** [comment]
Setting this to won't have as it would be a lot to try to implement before the deadline. Mapping pause menu functions to keys instead.
