### ISSUE TITLE
User story - Konami Code Easter Egg

### ISSUE THREAD

**Issue by adamgilroy22** [stephendawsondev/j-day#37]
### Story

As a **player**, I can **see an easter egg when I enter the Konami code (up up down down left right left right b a) on my keyboard** so that I can **be further immersed into the retro theme of the game**.

### Acceptance Criteria

- Some sort of message should appear when a user enters the Konami code
- If the user starts to enter the code pattern but makes a mistake, the pattern will reset and start looking for the first instance again

### Tasks

- [ ] Script should be created that listens to the keyboard for a specific pattern
- [ ] A counter should be in the script that increases as the user enters the correct keys in the code until the counter matches the length of the pattern
- [ ] If the user's keyboard input matches the pattern (Konami code), a message should appear or some sort of sound should play
- [ ] If the user makes a mistake in the pattern, the counter should reset to 0 until the first instance is entered again
