### ISSUE TITLE
User Story- Player Control

### ISSUE THREAD

**Issue by KTC96** [stephendawsondev/j-day#4]
### Story

As a **player**, I can **control a characters movement and shooting** so that I can **defeat incoming Terminators**.

### Acceptance Criteria

- The player character responds to arrow keys or WASD for movement.
- The player character shoots bullets using the spacebar.
- Bullets collide with Terminators and deal damage upon impact.

### Tasks

- [ ] Implement player character movement controls.
- [ ] Implement player character shooting mechanics.
- [ ] Define Terminator behavior upon bullet collision.

**Comment by stephendawsondev** [comment]
I think this is very important and a core feature of the game - I would suggest we could actually make this one an epic and break it down into more user stories. Controls on mobile vs. on desktop may have to be considered. 

Until we have all the required sprites, we can just use coloured boxes on the screen so that there's no blocker when implementing the collisions.

**Comment by Markyjay** [comment]
Split this story in to two stories, 
1. As a player, i can control a characters movement so that the user can move on a 2 dimensional background.
2. As a player, i can shoot from the character a laser type bullet so that the user can fire at incoming enemies.
