### ISSUE TITLE
User story - Using app on mobile

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#56]
### Story

As a **player**, I can **play the app on mobile** so that I can **play the game on the go**.

### Acceptance Criteria

- Canvas should be responsive so that it is usable on mobile.
- Player should be able to control the main character with direction buttons or a joystick.
- Player should be able to shoot/attack enemies.
- Difficulty should not be increase significantly with mobile usage.
- Map and sprites should be scaled appropriately.

### Tasks

- [ ] Dynamically calculate the width of the screen and pass it to the canvas.
- [ ] Add controls to mobile.
- [ ] Test to ensure it works as expected.
