### ISSUE TITLE
User Story - Score Tracking

### ISSUE THREAD

**Issue by KTC96** [stephendawsondev/j-day#6]
### Story

As a **player**, I can **earn points from each defeated Terminator** so that I can **track my in-game score**.

### Acceptance Criteria

- Player's score increases by a fixed amount for each defeated Terminator.
- The current score is displayed on the game screen.
- Points are accumulated and displayed accurately as Terminators are defeated.

### Tasks

- [x] Implement scoring system.
- [x] Integrate score display on the game interface.
- [x] Verify that the score increments correctly.

**Comment by stephendawsondev** [comment]
@moabdelbasset Thanks for taking this one. How are you getting with this one? Let me know if you want to have a huddle to discuss it. I know it might be a bit tricky if you haven't used Kaboom.js before. Also, to increase the score, it will be necessary to have both enemies and the main character. They are being handled in #4, #14 and #15, so you may want to sync up with @Koko-66 and @SasanTazayoni.

**Comment by adamgilroy22** [comment]
I have set this up, moving to done
