### ISSUE TITLE
User story - Bug-free experience

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/j-day#64]
### Story

As a **player**, I can **play the game without encountering bugs** so that I can **enjoy my gaming experience**.

### Acceptance Criteria

- Player should be able to navigate between scenes (main game, instructions, game over and game) easily
- User actions should not cause unexpected behaviour
- Enemy characters should not behave unexpectedly
- Characters should not move through objects they aren't supposed to move through

### Tasks

- [ ] Carry out player tests
- [ ] Carry out enemy character tests
- [ ] Carry out UI usability tests
