### ISSUE TITLE
User Story - Difficulty Progression

### ISSUE THREAD

**Issue by KTC96** [stephendawsondev/j-day#7]
### Story

As a **player**, I can **face increasing difficulty over time** so that I can **be challenged**.

### Acceptance Criteria

- Terminators gradually increase in speed and spawn rate.
- The rate of difficulty increase feels gradual and manageable.
- The game remains enjoyable and doesn't become overwhelmingly difficult too quickly.

### Tasks

- [ ] Design a simple difficulty scaling algorithm.
- [ ] Adjust Terminator attributes (speed, spawn rate) based on the difficulty level.
- [ ] Playtest to ensure a balanced and engaging difficulty progression.

**Comment by stephendawsondev** [comment]
I like this. Do you think we could label it as `should have`? It's really nice functionality, but also the game would function without it. 

Another idea might be to add the enemy type - maybe the terminator metal is a different, strong colour so it would actually have more hitpoints.
