### ISSUE TITLE
User story - Game Over

### ISSUE THREAD

**Issue by adamgilroy22** [stephendawsondev/j-day#77]
### Story

As a **player**, I can **get a game over screen when I die** so that I can **see my final score and be given the option to try again or quit**.

### Acceptance Criteria

- Once the player's life reaches 0, a game over screen should show alerting them of the fact
- From the game over screen, the player should be allowed to either start the game again or quit to the main menu
- The player should also be able to see their final score from this screen

### Tasks

- [x] Lives should decrease when hit
- [x] When lives reach 0, the game over scene should be loaded
- [x] Game over music should play when the scene loads
- [x] Users should see their final score on the game over screen
- [x] Users should be able to either restart the game or quit to the menu from the game over screen

**Comment by stephendawsondev** [comment]
@adamgilroy22 It looks like this one is finished, right? I'll leave you to close it if it is!
