### ISSUE TITLE
User Story - Design

### ISSUE THREAD

**Issue by KTC96** [stephendawsondev/j-day#8]
### Story

As a **player**, I can **observe a retro Terminator themed visual and audio design** so that I can **immerse myself in the nostalgic atmosphere of the game**.
 
### Acceptance Criteria

- Sound effects include classic arcade-style gunfire and explosion sounds.
- Game graphics have a pixel-art style reminiscent of retro games.
- The visual and audio design evoke a strong Terminator ambiance.

### Tasks

- [x] Design pixel-art sprites for characters, enemies, and objects.
- [x] Create and integrate retro-style sound effects.
- [x] Ensure visual and audio elements are cohesive and reflective of the Terminator theme.

**Comment by stephendawsondev** [comment]
This looks be done too. Closing off! Well done!
