### ISSUE TITLE
User story - Decrease life on collision with enemy

### ISSUE THREAD

**Issue by adamgilroy22** [stephendawsondev/j-day#88]
### Story

As a **player**, I can **lose a life when I collide with an enemy or their bullets** so that I can **get a game over screen when my lives hit 0**.

### Acceptance Criteria

- The player should lose a life when colliding with an enemy
- When the player's lives reach 0, a game over screen should show
- Player lives should be reset to 3 when they reset the page

### Tasks

- [x] Player lives decrease when getting hit
- [x] Game over screen displays when lives hit 0
- [x] Lives get reset when the user resets the game
